name: Manually Run ECS Task
description: Run an existing task in an existing AWS Service and Cluster

inputs:
  role-to-assume:
    description: IAM role
    required: true
  aws-region:
    description: AWS region to use
    required: true
    default: us-east-1
  cluster:
    description: ECS Cluster for Service
    required: true
  service:
    description: ECS Service for task to run
    required: true

runs:
  using: composite
  steps:
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
        mask-aws-account-id: true
    - name: Start ECS Task
      run: ${{ github.action_path }}/run_task.sh
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws-region }}
        CLUSTER: ${{ inputs.cluster }}
        SERVICE: ${{ inputs.service }}
